image: golang:1.7
stages:
 - build
 - test

before_script:
 - export GOPATH=$(dirname $CI_PROJECT_DIR)
 - go get github.com/tools/godep
 - export PATH=$PATH:$(go env GOPATH)/bin

build-my-project:
 stage: build
 script:
   - godep restore
   - godep go build

test-my-project:
 stage: test
 script:
   - godep restore
   - godep go test -v -cover ./...
