image: golang:1.7
stages:
 - build
 - test

before_script:
 - export GOPATH=$(dirname $CI_PROJECT_DIR)/go
 - go get github.com/tools/godep
 - go get gitlab.doc.ic.ac.uk/g1736215/MapNotes
 - cd /go/src/gitlab.doc.ic.ac.uk/g1736215/MapNotes

build-my-project:
 stage: build
 script:
   - godep restore
   - godep go build

test-my-project:
 stage: test
 script:
   - godep restore
   - godep go test -v -cover ./...
