image: golang:1.7

variables:
  REPO_NAME: gitlab.doc.ic.ac.uk/g1736215/MapNotes

stages:
 - build
 - test
 - deploy

before_script:
 - sudo apt-get -y -qq install ruby-dev golang-go
 - sudo gem install dpl
 - mkdir -p $HOME/go/src/$REPO_NAME
 - export GOPATH=$HOME/go
 - rsync -a $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
 - export PATH=$PATH:$(go env GOPATH)/bin
 - cd $GOPATH/src/$REPO_NAME
 - go get github.com/tools/godep
 - godep restore

build-mapnotes:
 stage: build
 script:
   - go install

test-mapnotes:
 stage: test
 script:
   - go test ./tests

deploy-mapnotes:
  stage: deploy
  only:
    - master
  script:
    - echo deploy
    - dpl --provider=heroku --app=mapnotes-backend --api-key=$HEROKU_STAGING_API_KEY
